# Generated by Django 2.0.5 on 2018-05-12 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_side', models.CharField(max_length=50)),
                ('flipped_side', models.CharField(max_length=200)),
                ('isLearned', models.BooleanField(default=False)),
                ('dateIsLearned', models.DateTimeField()),
                ('remindingDayCount', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
            ],
        ),
    ]
