# Generated by Django 2.0.5 on 2018-05-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_side', models.CharField(max_length=50)),
                ('flipped_side', models.CharField(max_length=200)),
                ('isLearned', models.BooleanField(default=False)),
                ('dateIsLearned', models.DateTimeField(blank=True)),
                ('remindingDayCount', models.IntegerField(default=1)),
            ],
        ),
    ]
