# Generated by Django 2.0.5 on 2018-05-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='category',
        ),
    ]
