# Generated by Django 2.0.5 on 2018-05-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_remove_card_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='dateIsLearned',
            field=models.DateField(),
        ),
    ]
